whatsappNumber: '527681022729'
launchDate: '2026-09-01T00:00:00-06:00'
facebookUrl: 'https://facebook.com/posatienda'
instagramUrl: 'https://instagram.com/posatienda'
linkedinUrl: 'https://linkedin.com/company/pos-atienda'
xUrl: 'https://x.com/posatienda'
