export const CONFIG = {

    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_ADMIN_EMAIL: process.env.RESEND_ADMIN_EMAIL,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    RESEND_TEMPLATE_ID_CONTACT: process.env.RESEND_TEMPLATE_ID_CONTACT,

}